### ISSUE TITLE
Switch coverage to codecov

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/DifferenceEquations.jl#100]
Unlike most packages in SciML, DifferenceEquations uses coveralls for CI.
Could we replace this with codecov?
That way all results are in the same place, and the maintenance burden is reduced.
We could also double up if the output of coveralls is wanted.

**Comment by ChrisRackauckas** [comment]
Yes, it should be made uniform.

**Comment by ArnoStrouwen** [comment]
Completed by https://github.com/SciML/DifferenceEquations.jl/pull/101.
